---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: devops-toolkit
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/haroldo89/devops-app-flux-helm.git

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: devops-toolkit-angular
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: devops-toolkit
  interval: 30s
  targetNamespace: angular
  values:
    image:
      repository: haroldo89/front-app
      tag: "68"
    replicaCount: 1
    service:
      nodePort: 32200
      port: 80
      targetPort: 80
      type: NodePort

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: devops-toolkit-nodejs
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: devops-toolkit
  interval: 30s
  targetNamespace: nodejs
  values:
    image:
      repository: haroldo89/server-app
      tag: "2.0"
    replicaCount: 1
    service:
      nodePort: 32300
      port: 80
      targetPort: 3000
      type: NodePort

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: devops-toolkit-angular
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: devops-toolkit
  interval: 30s
  targetNamespace: angular
  values:
    image:
      repository: haroldo89/front-app
      tag: "69"
    replicaCount: 1
    service:
      nodePort: 32200
      port: 80
      targetPort: 80
      type: NodePort

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: devops-toolkit-nodejs
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: devops-toolkit
  interval: 30s
  targetNamespace: nodejs
  values:
    image:
      repository: haroldo89/server-app
      tag: "2.0"
    replicaCount: 2
    service:
      nodePort: 32300
      port: 80
      targetPort: 3000
      type: NodePort

